dataset:
  name: Carla
  type: range_samples_from_image
  args:
    directory: /media/user/storage/data/ # ./dataset/Carla # /media/user/storage/data/sem_test
    scene_ids:
      - Town01
      - Town02
      - Town03
      - Town04
      - Town05
      - Town06
    res_in: '16_1024' # 16_1024
    res_out: '256_2048' # 128_2048
    num_of_samples: 16384
    memory_fetch: false

model:
  name: iln
  output: ./models/trained/iln_4d
  args:
    d: 2
    h: 8